# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addreass', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('pid',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.AddressInfo', verbose_name='自关联')),
            ],
        ),
    ]
