# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressinfo',
            old_name='addreass',
            new_name='address',
        ),
    ]
