# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0002_auto_20181021_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressinfo',
            options={'ordering': ['pid'], 'verbose_name': '省市县地址信息', 'verbose_name_plural': '省市县地址信息'},
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='说明'),
        ),
        migrations.AlterUniqueTogether(
            name='addressinfo',
            unique_together=set([('address', 'note')]),
        ),
        migrations.AlterModelTable(
            name='addressinfo',
            table='address',
        ),
    ]
