# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0005_auto_20181024_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressinfo',
            options={'verbose_name': '省市县地址信息', 'verbose_name_plural': '省市县地址信息'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['age'], 'verbose_name': '学生信息表', 'verbose_name_plural': '学生信息表'},
        ),
    ]
